full_data <- read.csv("household_power_consumption.txt", header = TRUE, sep = ';', na.strings = "?", nrows = 2075259, check.names = FALSE, stringsAsFactors = FALSE, comment.char = "", quote = '\"')
data_1 <- subset(full_data, Date %in% c("1/2/2007", "2/2/2007"))
data_1$date <- as.Date(data_1$Date, format="%d/%m/%Y")
hist(data_1$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", ylab = "Frequency", col="red")
png("plot1.png", width = 480, height = 480)
dev.off()